### ISSUE TITLE
Vimeo API blocked when used on HTTPS

### ISSUE THREAD

**Issue by biegl** [DominikAngerer/videojs-vimeo#1]
I am using the plugin on a website that is using HTTPS. Chrome blocks the request to 'http://www.vimeo.com/api/v2/video/':
```
This request has been blocked; the content must be served over HTTPS.
```
I think the API url should not be hard-coded or use HTTPS by default.

Bests,

**Comment by DominikAngerer** [comment]
Hello Markus,

Thank you for using the plugin - as you  can see in the description of this project I've made a hardcopy of: https://github.com/videojs/videojs-vimeo and fixed a major bug for an private project. You can use this repository (with the bugfix) with `npm i videojs-vimeo-v2`. I've also included a bugfix (6cfa9835f381464001bce1f52be4c4849eb633d5) for this issue.



Br,
Dominik
